### PR TITLE
Player Sprites

### PR DESCRIPTION
**Pull request by Acpeters**
Added the basic player movement sprites along with sprites for when the player is holding a slingshot.

### CODE REVIEW

**Review by BrandonJamieson — APPROVED** [review]
Sprites look great! No complaints here.

**Comment by sanche21** [comment]
Looks good to me. My only concern is camera movement. Can the inventory move with the camera? I can't tell since the camera is locked here, but it's probably pretty important to the inventory feature. Also, the text is super small, but we can probably fix that some other time

**Comment by daniel-sanche** [comment]
looks good to me, you'll just need to merge master into it before you can merge it into master

**Comment by daniel-sanche** [comment]
I'll close this one since you made a new one

**Pull request closed without merging**
