### PR TITLE
Inventory

### PR DESCRIPTION
**Pull request by BrandonJamieson**
Added Inventory script as well as several functionality scripts (Slots, WeaponSlots, InventoryDatabase, Item, Weapon, Regeneration, Barricade). It can be enabled/disabled by pressing the configured button and makes use of several prefabs for performing its operations. For dropping functionality to work properly, there must be a gameobject tagged "Player" in the scene. Items can be attached to the pickup prefab to be picked up by the player.

### CODE REVIEW

**Comment by Acpeters** [comment]
Looks good

**Comment by daniel-sanche** [comment]
Actually one issue: It looks like you added the Library folder and a bunch of subfolders. There aren't supposed to be synced, and it caused some pretty big issues switching between branches (I had to delete the repo a couple times before I figured out the problem). Could you remove those files from the repo?

**Comment by daniel-sanche** [comment]
Also, I'm wondering about camera movement. Can the inventory move with the camera? I can't tell since the camera is locked here, but it's probably pretty important to the inventory feature. Also, the text is super small, but we can probably fix that some other time

**Review by daniel-sanche — APPROVED** [review]
You can probably merge this any time, it looks good to me

**Pull request merged**
